Feat/metafields
factly/dega pull request #328
Opened 2021-07-12 12:03 UTC by Bhumi101097

Studio changes for meta fields and meta data
Closes #133 
Closes #132

2021-07-13 13:24 UTC, shreeharsha-factly requested changes

2021-07-13 13:24 UTC, shreeharsha-factly commented on studio/src/components/Template/index.js
> +  const { posts, loading } = useSelector((state) => {
Remove `media` on line 37 and 39

2021-07-13 13:24 UTC, shreeharsha-factly commented on studio/src/pages/claimants/components/ClaimantForm.js
> +
Function `getJsonVal` looks repeated in all form components. Add that function in utils.

2021-07-13 13:24 UTC, shreeharsha-factly commented on studio/src/pages/webhooks/components/WebhookForm.js
>      let total = 0;
Remove `total` and `loading` where ever it is not used.

2021-07-13 14:21 UTC, deshetti commented
@Bhumi101097 Please add the test cases as well for the functionality

2021-07-16 09:42 UTC, shreeharsha-factly approved these changes

2021-07-16 09:42 UTC, merged