Component/Sidebar Changes
factly/dega pull request #874
Opened 2023-03-14 10:31 UTC by tejveer777

- Add Space selector dropdown component
-  added searchbar on sidebar component and remove the icon according to figma
- Made changes to styling of sidebar
-

2023-03-14 12:06 UTC, vsumit89 requested changes

2023-03-14 12:06 UTC, vsumit89 commented on studio/src/actions/spaces.js
remove the console.log

2023-03-14 12:06 UTC, vsumit89 commented on studio/src/components/GlobalNav/Sidebar.js
> +          flexDirection: 'column',
can you explain this change?

2023-03-14 12:06 UTC, vsumit89 commented on studio/src/actions/spaces.js
> +  console.log('deleteSpace', id);
remove console.log

2023-03-14 12:15 UTC, vsumit89 approved these changes, later dismissed

2023-03-16 10:42 UTC, tejveer777 commented on studio/src/components/GlobalNav/Sidebar.js
> +          flexDirection: 'column',
to make the change the direction to be in column
figma-
![image](https://user-images.githubusercontent.com/127482564/225591826-90902610-9cd7-4612-9ec8-2297e1853968.png)
on develop branch
![image](https://user-images.githubusercontent.com/127482564/225592760-d7053560-afc2-462c-aa9c-4ca1a9f5f07d.png)

2023-03-21 09:49 UTC, surajmn1 requested changes
@tejveer777  please include only studio files and remove changes in docker-compose.yml , readme.md , volumes folders .

2023-05-12 07:00 UTC, merged